### ISSUE TITLE
Can you please include the timestamp of the test

### ISSUE THREAD

**Issue by kleinbottle** [showwin/speedtest-go#10]
I have been using speedtest-cli for a while, and recently took speedtest-go for a spin. It is good and reports almost everything I want except the timestamp of the test.

Would you please consider including the timestamp as well?

Thanks.

**Comment by showwin** [comment]
I'm sorry for really late response 😢 
How about using `date` command ?
```
$ speedtest && date
Testing From IP: 118.21.139.107 (NTT Communications) [35.7616, 139.2011]

Target Server: [6087]    12.35km Fussa-shi (Japan) by Allied Telesis Capital Corporation
Latency: 10.407305ms
Download Test: ................
Upload Test: ................

Download: 34.28 Mbit/s
Upload: 36.37 Mbit/s
Mon Apr 16 21:43:07 JST 2018  # timestamp added
```

**Comment by showwin** [comment]
If the solution is not enough, please reopen this issue.
