### ISSUE TITLE
arm版梅林固件运行报Illegal instruction

### ISSUE THREAD

**Issue by zxq1002** [showwin/speedtest-go#11]
arm版本在qnap ts-231+上运行没问题，但网件R6300V2梅林固件运行提示Illegal instruction
cpu都是arm架构

**Comment by showwin** [comment]
Hi, thank you for reporting a bug.
I found a related issue you create https://github.com/zpeters/speedtest/issues/109.

You might download a compiled version of `speedtest-go`, is't it?
How about cloning this repo and build from source.
