### ISSUE TITLE
Abstract Speedtest Implementation to Own Package

### ISSUE THREAD

**Issue by cbergoon** [showwin/speedtest-go#12]
I have a use case for a speedtest within another project. Would you be interested in accepting PR that abstracts the implementation of the speedtest to its own package? 

I will submit a PR shortly.

CMB

**Comment by showwin** [comment]
Refactoring is finally merged into master branch by https://github.com/showwin/speedtest-go/pull/20.
Thanks a lot ⭐ 

and very sorry for late action 🙏
