### ISSUE TITLE
Request to add support for s390x architecture

### ISSUE THREAD

**Issue by spiritLHLS** [showwin/speedtest-go#123]
Request to add support for s390x architecture

I was surprised to find out that the CLI introduction of speedtest.net does not support the s390x architecture when I built the shell automation speed test script.

**Comment by r3inbowari** [comment]
https://github.com/showwin/speedtest-go/releases/download/v1.6.0/speedtest-go_1.6.0_Linux_s390x.tar.gz

**Comment by spiritLHLS** [comment]
I saw it, thanks.
