### ISSUE TITLE
Low upload speed

### ISSUE THREAD

**Issue by pradeepbbl** [showwin/speedtest-go#137]
Hey, Thanks for the awesome lib it work great I'm using it in Prometheus custom exporter running the test every 5m so far work great only issue am having is low upload speed as compare to manual run using speedtest.net. Is anyone know hot fix or improve the upload speed.

```
# HELP test_speedtest_download Download speed (bit/s)
# TYPE test_speedtest_download gauge
test_speedtest_download{city="xxxx",country="xxxx",provider="xxxx"} 874.6208
# HELP test_speedtest_latency Latency (ms)
# TYPE test_speedtest_latency gauge
test_speedtest_latency{city="xxx",country="xxx",provider="xxxxx"} 9
# HELP test_speedtest_upload Upload speed (bit/s)
# TYPE test_speedtest_upload gauge
test_speedtest_upload{city="xxx",country="xxx",provider="xxxx"} 318.1458 (half the speed in web it was 800+)
```

**Comment by r3inbowari** [comment]
Thank you, @pradeepbbl. Is multi mode enabled?

**Comment by r3inbowari** [comment]
![image](https://github.com/showwin/speedtest-go/assets/30739857/cdbdda56-56bd-4321-a8ca-9bccfec8a555)
I test on ～5Gbps/10Gbps(up/down) cloud server. It almost got the max bandwidth.

**Comment by pradeepbbl** [comment]
hey @r3inbowari sorry for the delay response am making the api call instead using the cli with `NThread` set to 4, but using cli with `--multi` also provide similar result

**Comment by r3inbowari** [comment]
I guess this is due to the bandwidth limit of the server. You can adjust the connection number(-t 8 or NThread = 8), according to speedtest-cli this number should be 8. And then it will connect to more different servers.

**Comment by cxnky** [comment]
also getting this.


✓ Test Server: [22069] 0.09km New York, NY (United States) by TeleBermuda International Limited
✓ Latency: 1.099015ms Jitter: 334.839µs Min: 813.339µs Max: 1.942636ms
✓ Download: 0.00Mbps (used: 0.00MB)
✓ Upload: 0.00Mbps (used: 0.00MB)

**Comment by r3inbowari** [comment]
> also getting this.
> 
> ✓ Test Server: [22069] 0.09km New York, NY (United States) by TeleBermuda International Limited ✓ Latency: 1.099015ms Jitter: 334.839µs Min: 813.339µs Max: 1.942636ms ✓ Download: 0.00Mbps (used: 0.00MB) ✓ Upload: 0.00Mbps (used: 0.00MB)

This is an unreachable server. related to #162
