### ISSUE TITLE
Using API wrong results

### ISSUE THREAD

**Issue by gressdave58** [showwin/speedtest-go#138]
Recursive calls thru the api result in cumulative test speeds

./speedtest 
test i: 1
Latency: 29.58471ms, Download: 85.848700, Upload: 6.527300
test i: 2
Latency: 49.067701ms, Download: 162.878500, Upload: 12.465000
test i: 3
Latency: 29.116814ms, Download: 241.038000, Upload: 16.620100
test i: 4
Latency: 30.173995ms, Download: 310.099500, Upload: 22.099200

* 1st test correct as i only have a 100Mb pipe here

------- Example api used with loop --------------
package main

import (
	"fmt"
	"github.com/showwin/speedtest-go/speedtest"
)

func main () {
   var i = 0
   for i = 1; i < 5; i++ {
       fmt.Println("test i:", i)
       Speed()
   }
}

func Speed() {
	var speedtestClient = speedtest.New()
	
	// Use a proxy for the speedtest. eg: socks://127.0.0.1:7890
	// speedtest.WithUserConfig(&speedtest.UserConfig{Proxy: "socks://127.0.0.1:7890"})(speedtestClient)
	
	// Select a network card as the data interface.
	// speedtest.WithUserConfig(&speedtest.UserConfig{Source: "192.168.1.101"})(speedtestClient)
	
	// Get user's network information
	// user, _ := speedtestClient.FetchUserInfo()
	
	// Get a list of servers near a specified location
	// user.SetLocationByCity("Tokyo")
	// user.SetLocation("Osaka", 34.6952, 135.5006)
    
	// Search server using serverID.
	// eg: fetch server with ID 28910.
	// speedtest.ErrServerNotFound will be returned if the server cannot be found.
	// server, err := speedtest.FetchServerByID("28910")
	
	serverList, _ := speedtestClient.FetchServers()
	targets, _ := serverList.FindServer([]int{})
 
	for _, s := range targets {
		// Please make sure your host can access this test server,
		// otherwise you will get an error.
		// It is recommended to replace a server at this time
		s.PingTest(nil)
		s.DownloadTest()
		s.UploadTest()
		fmt.Printf("Latency: %s, Download: %f, Upload: %f\n", s.Latency, s.DLSpeed, s.ULSpeed)
	}
}

**Comment by r3inbowari** [comment]
call `speedtest.GlobalDataManager.Reset()` per loop

**Comment by gressdave58** [comment]
Thank you !  works great..

gressd@gressdXCTVY playArea % ./speedtest          
test i: 1
Latency: 30.75361ms, Download: 51.833800, Upload: 4.718500
test i: 2
Latency: 101.140129ms, Download: 50.479700, Upload: 5.321500
test i: 3
Latency: 41.913447ms, Download: 54.333900, Upload: 5.452500
test i: 4
Latency: 64.321012ms, Download: 54.786500, Upload: 4.220500
