### ISSUE TITLE
Crashes when latency can't be detected

### ISSUE THREAD

**Issue by laffer1** [showwin/speedtest-go#140]
version 1.6.3

When running a test, if it happens to pick servers it can't do a latency test for, it just dies. 

✓ Test Server: [39292] 10.91km Ann Arbor, MI (United States) by University of Michigan
✗ Fatal: latency: , err: server connect timeout

Seems to happen when http ping is needed. Perhaps add a warning about that?

**Comment by r3inbowari** [comment]
Do you want to skip the latency test?

**Comment by laffer1** [comment]
In this case, that would have been useful.  I have been debugging some issues with a switch and just wanted to get downstream results.

**Comment by r3inbowari** [comment]
Could you provide an improved template, thanks!
