### ISSUE TITLE
No asset is released at v1.6.4

### ISSUE THREAD

**Issue by suzuki-shunsuke** [showwin/speedtest-go#143]
v1.6.4 has no assets.

https://github.com/showwin/speedtest-go/releases/tag/v1.6.4

<img width="562" alt="image" src="https://github.com/showwin/speedtest-go/assets/13323303/9a7376d1-b761-45e8-b018-8e4dd8f7facc">

GoReleaser failed.

https://github.com/showwin/speedtest-go/actions/runs/5955363923/job/16153933697

**Comment by suzuki-shunsuke** [comment]
I'll send a pull request to resolve this issue soon.

**Comment by suzuki-shunsuke** [comment]
I could reproduce the issue on my laptop.

v1.20.0 was used.

https://github.com/showwin/speedtest-go/actions/runs/5955363923/job/16153933697#step:4:11

```console
$ goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.20.0
GitCommit:     56c9d09a1b925e2549631c6d180b0a1c2ebfac82
GitTreeState:  false
BuildDate:     2023-08-10T01:23:44Z
BuiltBy:       goreleaser
GoVersion:     go1.21.0
Compiler:      gc
ModuleSum:     h1:wvAbDqQwMX3PWPYc4VIeaWQB2V5HOETvDlyfTrk7NgQ=
Platform:      darwin/arm64
```

```console
$ goreleaser release --clean --snapshot
  • starting release...
  • loading config file                              file=.goreleaser.yml
  ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 39: field replacements not found in type config.Archive
```

**Comment by suzuki-shunsuke** [comment]
https://goreleaser.com/deprecations/?h=replacements#archivesreplacements

`archives.replacement` was removed.

> You can still get the same features by abusing the name_template property.

**Comment by showwin** [comment]
✅  [v.1.6.5](https://github.com/showwin/speedtest-go/releases/tag/v1.6.5) contains release assets. 

@suzuki-shunsuke Thanks for your fix!
