### ISSUE TITLE
-t 1 Results Not as Expected

### ISSUE THREAD

**Issue by i-abc** [showwin/speedtest-go#148]
Hi, I want to run speedtest with a single connection, but I meet some questions as the output from speedtest-go doesn't match my expectation, and it seems to provide lower results.

[speedtest-go](https://github.com/showwin/speedtest-go) -t 1, output:

```
root@Azure-Linux:~# ./speedtest-go -s 48463 -t 1

    😊 speedtest-go v1.6.5 @showwin 😊

✓ ISP: 20.222.146.* (Microsoft Corporation) [37.751, -97.822] 
✓ Found 20 Public Servers

✓ Test Server: [48463] 9936.46km Tokyo (Japan) by IPA CyberLab 400G
✓ Latency: 2.72078ms Jitter: 225.86µs Min: 2.457142ms Max: 3.247406ms
✓ Download: 421.09Mbps (used: 501.98MB)
✓ Upload: 22.39Mbps (used: 26.69MB)
```

[speedtest-cli](https://github.com/sivel/speedtest-cli) --single, output:

```
root@Azure-Linux:~# speedtest-cli --server 48463 --single
Retrieving speedtest.net configuration...
Testing from Microsoft Corporation (20.222.146.*)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by IPA CyberLab 400G (Tokyo) [9925.34 km]: 7.823 ms
Testing download speed................................................................................
Download: 1111.62 Mbit/s
Testing upload speed......................................................................................................
Upload: 607.73 Mbit/s
```

There is a significant difference between the two outputs, especially in the upload speed. 

Furthermore, the distance displayed seems to be incorrect. My server is located in Tokyo, and the latency of 2.72078ms can confirm this, but the output shows "9936.46km".

**Comment by r3inbowari** [comment]
Hello, @i-abc, Thanks for pointing it out. I need to clarify that in speedtest-cli, `--single` refers to using only one server for speed testing. This does not mean using one thread for speed testing.

**Comment by r3inbowari** [comment]
Therefore, I think `--single` should be equivalent to `-t 8`

> Hello, @i-abc, Thanks for pointing it out. I need to clarify that in speedtest-cli, `--single` refers to using only one server for speed testing. This does not mean using one thread for speed testing.

**Comment by r3inbowari** [comment]
Sorry, I mistaken speedtest-cli for the official software.

**Comment by r3inbowari** [comment]
```shell
xxx@xxx:~$ ./speedtest-go -s 48463 -t 1

    speedtest-go v1.6.5 at showwin

✓ ISP: x.x.x.x (Google) [x, x] 
✓ Found 1 Specified Public Servers

✓ Test Server: [48463] 0.00km Tokyo () by IPA CyberLab 400G
✓ Latency: 70.893687ms Jitter: 20.532353ms Min: 59.215306ms Max: 132.049069ms
✓ Download: 284.44Mbps (used: 339.07MB)
✓ Upload: 21.03Mbps (used: 25.06MB)

xxx@xxx:~$ pip install speedtest-cli
Collecting speedtest-cli
  Downloading speedtest_cli-2.1.3-py2.py3-none-any.whl (23 kB)
Installing collected packages: speedtest-cli
Successfully installed speedtest-cli-2.1.3

xxx@xxx:~$ speedtest-cli --server 48463 --single
Retrieving speedtest.net configuration...
Testing from Google (x.x.x.x)...
Retrieving speedtest.net server list...
ERROR: No matched servers: 48463
```

Due to regional restrictions and the old API used by sivel/speedtest-cli, I can't find this server in sivel/speedtest-cli.

**Comment by r3inbowari** [comment]
![image](https://github.com/showwin/speedtest-go/assets/30739857/a40dc876-c7cf-481d-9d69-69361c8043fe)

**Comment by r3inbowari** [comment]
![1694066419224](https://github.com/showwin/speedtest-go/assets/30739857/2e1d1794-4ead-49d6-98cb-d9e3722b548f)

**Comment by r3inbowari** [comment]
![image](https://github.com/showwin/speedtest-go/assets/30739857/552b6049-f763-4a53-b3bc-212b6d2ba969)

**Comment by r3inbowari** [comment]
> I have one more question. If I want to achieve a similar effect to the "single" option in the web version of speedtest.net, what should the value of the "-t" parameter be set to?

`speedtest-go` (only http)
1. single refers to using one single server (one server, t connections)
2. multi refers to using multiple servers (repeating selection t times in a known server sequence)

`speedtest.net` (websocket and http)
1. single refers to using one  single server (one server, one connection)
2. multi refers to using multiple servers (default 8 servers, one connection per server)
