### ISSUE TITLE
linux error:signal: killed

### ISSUE THREAD

**Issue by pabcxyz** [showwin/speedtest-go#149]
"In macOS, this is no issue. However, when running on Linux, the following error occurs: signal: killed."
Code:
`package main

import (
	"fmt"
	"github.com/showwin/speedtest-go/speedtest"
)

func main() {
	var speedtestClient = speedtest.New()
	
	// Use a proxy for the speedtest. eg: socks://127.0.0.1:7890
	// speedtest.WithUserConfig(&speedtest.UserConfig{Proxy: "socks://127.0.0.1:7890"})(speedtestClient)
	
	// Select a network card as the data interface.
	// speedtest.WithUserConfig(&speedtest.UserConfig{Source: "192.168.1.101"})(speedtestClient)
	
	// Get user's network information
	// user, _ := speedtestClient.FetchUserInfo()
	
	// Get a list of servers near a specified location
	// user.SetLocationByCity("Tokyo")
	// user.SetLocation("Osaka", 34.6952, 135.5006)
    
	// Search server using serverID.
	// eg: fetch server with ID 28910.
	// speedtest.ErrServerNotFound will be returned if the server cannot be found.
	// server, err := speedtest.FetchServerByID("28910")
	
	serverList, _ := speedtestClient.FetchServers()
	targets, _ := serverList.FindServer([]int{})

	for _, s := range targets {
		// Please make sure your host can access this test server,
		// otherwise you will get an error.
		// It is recommended to replace a server at this time
		s.PingTest(nil)
		s.DownloadTest()
		s.UploadTest()
		fmt.Printf("Latency: %s, Download: %f, Upload: %f\n", s.Latency, s.DLSpeed, s.ULSpeed)
	}
}`

**Comment by r3inbowari** [comment]
Hi, @pabcxyz, Can I use strace or dmesg for debugging.

**Comment by pabcxyz** [comment]
@r3inbowari    [https://github.com/showwin/speedtest-go/issues/95](url) ,In this issue, you mentioned a .zip file that worked for me. Where can I find the corresponding code?

**Comment by r3inbowari** [comment]
> @r3inbowari [https://github.com/showwin/speedtest-go/issues/95](url) ,In this issue, you mentioned a .zip file that worked for me. Where can I find the corresponding code?

They use almost the same code. use speedtest-go@v1.4.0

**Comment by r3inbowari** [comment]
```
var speedtestClient = speedtest.New()
# Try adding debug line, can you see anything?
speedtest.WithUserConfig(&speedtest.UserConfig{Debug: true})(speedtestClient)
```

**Comment by r3inbowari** [comment]
[speedtest-go_linux_amd64.zip](https://github.com/showwin/speedtest-go/files/12564450/speedtest.zip)

**Comment by pabcxyz** [comment]
@r3inbowari This .zip file doesn't work; it has the same issue as the one I mentioned.

**Comment by pabcxyz** [comment]
@r3inbowari  server  A is configured with 4 vCPUs and 8 GiB of RAM, server B is configured with 4 vCPUs and 16 GiB of RAM. When I run the program on server A, it throws this error, but it works fine on server B. I believe this program has specific memory requirements. I hope for a quick fix.now,What should I do now to be able to use this package? Could you please advise?

**Comment by r3inbowari** [comment]
Can you provide system information

**Comment by pabcxyz** [comment]
@r3inbowari Sure, but what specific system information do you need?

**Comment by r3inbowari** [comment]
kernel and os release

**Comment by pabcxyz** [comment]
CentOS Linux release 7.6.1810 (Core)

**Comment by r3inbowari** [comment]
A and B are same?

**Comment by pabcxyz** [comment]
Yes, apart from the system configuration。

**Comment by r3inbowari** [comment]
Any clues about dmesg?

> Hi, @pabcxyz, Can I use strace or dmesg for debugging.

**Comment by pabcxyz** [comment]
<img width="665" alt="image" src="https://github.com/showwin/speedtest-go/assets/8225375/901ae585-9c81-4b2a-a165-9e8040dfe1b1">
<img width="796" alt="image" src="https://github.com/showwin/speedtest-go/assets/8225375/1b20bbdf-f8da-4f98-ac25-56182892aea3">
I only captured a fragment.

**Comment by r3inbowari** [comment]
where is the kill signal you mentioned?

**Comment by pabcxyz** [comment]
<img width="698" alt="image" src="https://github.com/showwin/speedtest-go/assets/8225375/48e0d660-6a40-4ca5-ac34-7493a800bb86">

**Comment by r3inbowari** [comment]
oom?

**Comment by r3inbowari** [comment]
> Any clues about dmesg?
> 
> > Hi, @pabcxyz, Can I use strace or dmesg for debugging.

```shell
dmesg | egrep -i -B100 'killed process'
```

**Comment by pabcxyz** [comment]
Sorry, I didn't quite understand what you meant. Currently, this is all I can provide.

**Comment by r3inbowari** [comment]
> Sorry, I didn't quite understand what you meant. Currently, this is all I can provide.

add my wx with same id 😊.

**Comment by r3inbowari** [comment]
This issue seems to occur after https://github.com/showwin/speedtest-go/pull/142.
