### ISSUE TITLE
Hidden cursor after listing available servers

### ISSUE THREAD

**Issue by petrkutalek** [showwin/speedtest-go#171]
After listing the available servers using the `speedtest-go -l` command, the system cursor is not restored correctly and is hidden. To fix it, you need to use the `reset` command or similar. When taking measurements, displaying help, etc., this does not happen and everything is fine.

I guess it has something to do with quitting the application via [`os.Exit(1)`](https://github.com/showwin/speedtest-go/blob/master/speedtest.go#L102).

Used version: `speedtest-go v1.6.10 @showwin`

Compare pictures below

![wrong](https://github.com/showwin/speedtest-go/assets/42769564/5b13054f-41cc-48c8-addd-b19442214de9)

vs 

![ok](https://github.com/showwin/speedtest-go/assets/42769564/b09c169b-9a8a-4418-9a0b-1f0a658f4d89)

**Comment by r3inbowari** [comment]
> I guess it has something to do with quitting the application via [`os.Exit(1)`](https://github.com/showwin/speedtest-go/blob/master/speedtest.go#L102).

Have you tried it? If so, you can push a PR, thanks!

**Comment by r3inbowari** [comment]
Changed, please reopen if there is any problem.

**Comment by luevano** [comment]
Hey @r3inbowari, I still see the same issue from my end. Using version `speedtest-go v1.7.7 git-dev built at unknown` (from AUR), I believe this version should have included the fix from #176 .

**Comment by r3inbowari** [comment]
> Hey @r3inbowari, I still see the same issue from my end. Using version `speedtest-go v1.7.7 git-dev built at unknown` (from AUR), I believe this version should have included the fix from #176 .

Hi, @luevano Does it work when you use `--unix`?

**Comment by luevano** [comment]
> > Hey @r3inbowari, I still see the same issue from my end. Using version `speedtest-go v1.7.7 git-dev built at unknown` (from AUR), I believe this version should have included the fix from #176 .
> 
> Hi, @luevano Does it work when you use `--unix`? And what command did you use?

Actually yes

**Comment by r3inbowari** [comment]
> > > Hey @r3inbowari, I still see the same issue from my end. Using version `speedtest-go v1.7.7 git-dev built at unknown` (from AUR), I believe this version should have included the fix from #176 .
> 
> > 
> 
> > Hi, @luevano Does it work when you use `--unix`? And what command did you use?
> 
> 
> 
> Actually yes

Could you report your environment?

**Comment by luevano** [comment]
> > > > Hey @r3inbowari, I still see the same issue from my end. Using version `speedtest-go v1.7.7 git-dev built at unknown` (from AUR), I believe this version should have included the fix from #176 .
> > 
> > 
> > > 
> > 
> > 
> > > Hi, @luevano Does it work when you use `--unix`? And what command did you use?
> > 
> > 
> > Actually yes
> 
> Could you report your environment?

What specifics do you need from the environment? literally the output of `env`?

I'm running arch on `linux 6.9.3.arch1-1`, using `bash` and it happens outside and inside `tmux`. I'm also connected through `ssh`. Some output of `env`, removed everything with my `/home/username` in it:

```
SHELL=/bin/bash
LESSHISTFILE=-
LESS=-R
HISTSIZE=10000
LESS_TERMCAP_se=
LESS_TERMCAP_so=
GPG_TTY=/dev/pts/15
EDITOR=nvim
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;35:ln=04;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SSH_CONNECTION=192.168.1.101 61690 192.168.1.100 22
TERM=xterm-256color
LESS_TERMCAP_mb=
LESS_TERMCAP_me=
LESS_TERMCAP_md=
SUDO_EDITOR=nvim
VISUAL=nvim
LESS_TERMCAP_ue=
SHLVL=1
LESS_TERMCAP_us=
SSH_CLIENT=192.168.1.101 61690 22
DEBUGINFOD_URLS=https://debuginfod.archlinux.org
SSH_TTY=/dev/pts/15
_=/usr/bin/env
```

**Comment by r3inbowari** [comment]
ssh
![image](https://github.com/showwin/speedtest-go/assets/30739857/1ff660eb-dae5-4eca-8caa-eeeb07b7048e)

tmux with ssh
![image](https://github.com/showwin/speedtest-go/assets/30739857/1e66512a-44e3-46d6-bc40-42ec205282cf)

![image](https://github.com/showwin/speedtest-go/assets/30739857/301e5a29-0cfe-49f5-8301-8e1904ed8670)

I can not reproduce😕

**Comment by luevano** [comment]
Gotcha, not sure what is the issue then, if I come by a solution I'll open a PR. This is not too much of an issue for me, just wanted to report it. Ty!
