### ISSUE TITLE
Zero download speed at times

### ISSUE THREAD

**Issue by Terrance** [showwin/speedtest-go#182]
On several occassions I've found the download speed to be reported as zero:

```
$ speedtest-go

    speedtest-go v1.6.10 @showwin

✓ ISP: ...
✓ Found 20 Public Servers

✓ Test Server: ...
✓ Latency: 8.735036ms Jitter: 851.809µs Min: 7.714099ms Max: 10.439103ms
✓ Download: 0.00Mbps (used: 0.00MB) (latency: 8ms jitter: 0ms min: 6ms max: 9ms)
✓ Upload: 95.58Mbps (used: 113.94MB) (latency: 8ms jitter: 0ms min: 7ms max: 11ms)
```

This happens both on Arch Linux (using the [speedtest-go AUR package](https://aur.archlinux.org/packages/speedtest-go)) and on Android in Termux (also 1.6.10), though it seems to be a temporary issue that comes and goes -- download speed is currently reported correctly (~450Mbps) on both devices.

Running with `-d` I can see the download URL being repeatedly logged, whether the speed is being reported correctly or not:

```
[DBG]2024/03/07 22:11:00 XdlURL: http://...:8080/speedtest/random1000x1000.jpg
```

**Comment by r3inbowari** [comment]
I think this is caused by the third-party server being temporarily unreachable. Does this always happen on a certain server?

**Comment by Terrance** [comment]
It's possible, will keep an eye on it and make a note of the host next time it happens (tried a few times today but yet to repro).

**Comment by r3inbowari** [comment]
```shell

    speedtest-go v2.0.0-beta1 @showwin

✓ ISP: *.*.*.* (x x) [*, *]
✓ Found 1 Specified Public Servers

✓ Test Server: [9060] *km Norwich by Voicehost Ltd
✓ Latency: 294.17822ms Jitter: 53.580903ms Min: 238.36955ms Max: 448.8789ms
✓ Download: 0.00Mbps (used: 0.00MB) (latency: 276ms jitter: 15ms min: 235ms max: 295ms)
✓ Upload: 11.64Mbps (used: 13.88MB) (latency: 326ms jitter: 157ms min: 235ms max: 739ms)
```

Yes, I am able to reproduce this on this server.

**Comment by r3inbowari** [comment]
What is certain is that the server 9060 is actively rejecting download requests from user-agent `showwin/speedtest-go x.y.z`

**Comment by vaygr** [comment]
I can reproduce this issue with 53972 (Dish Wireless).

**Comment by r3inbowari** [comment]
> I can reproduce this issue with 53972 (Dish Wireless).

I think we can add a flag `--user-agent` to the cli, so that users can modify the default user-agent to avoid being banned by the server.

**Comment by r3inbowari** [comment]
```shell
# with default ua
.\speedtest-go.exe -s 9060

    speedtest-go v1.6.11 @showwin

✓ ISP: *.*.*.* (*) [*, *]
✓ Found 1 Specified Public Server(s)

✓ Test Server: [9060] *.*km Norwich by Voicehost Ltd
✓ Latency: 380.061155ms Jitter: 11.047864ms Min: 368.896ms Max: 404.33695ms
⠦ Download: 0.00Mbps (latency: 374ms)
```

```shell
# with specified ua
.\speedtest-go.exe -s 9060 --ua="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

    speedtest-go v1.6.11 @showwin

✓ ISP: *.*.*.* (*) [*, *]
✓ Found 1 Specified Public Server(s)

✓ Test Server: [9060] *.*km Norwich by Voicehost Ltd
✓ Latency: 189.173855ms Jitter: 63.365714ms Min: 163.31595ms Max: 377.1291ms
⠼ Download: 23.11Mbps (latency: 164ms)
```

**Comment by vaygr** [comment]
@r3inbowari thanks! Would it make sense to display `N/A` or some kind of error string instead of a confusing zero speed number in cases like this?

**Comment by r3inbowari** [comment]
```shell
⠦ Download: N/A Mbps (latency: 374ms)
```

```shell
⠦ Download: N/A (latency: 374ms)
```

or?

**Comment by vaygr** [comment]
The second one looks great to me.
