### ISSUE TITLE
'speedtest-go --version' no longer outputs an x.y.z string in speedtest-go (>= 1.7.7)

### ISSUE THREAD

**Issue by HenrikBengtsson** [showwin/speedtest-go#232]
Starting with speedtest-go 1.7.7, I no longer get pure `x.y.z` numeric output, but:

```sh
$ speedtest-go --version
speedtest-go v1.7.9 git-dd78c65 built at 2024-09-04T11:40:23Z

$ speedtest-go --version
speedtest-go v1.7.7 git-8e02144 built at 2024-05-16T11:07:08Z

$ speedtest-go --version
1.7.6

$ speedtest-go --version
1.6.10
```

Since it's not mentioned in the change log, I suspect this is a mistake.

**Comment by r3inbowari** [comment]
chore: add hash commit and date for release (#217) 

sorry, it's not a mistake. it just forgot to write into the changelog.
