### ISSUE TITLE
supplied speedtest-go binary will not run on OpenBSD 7.5 GENERIC.MP

### ISSUE THREAD

**Issue by void-fm** [showwin/speedtest-go#233]
./speedtest-go 
speedtest-go:./speedtest-go: undefined symbol 'syscall'
ld.so: speedtest-go: lazy binding failed!
Killed

**Comment by void-fm** [comment]
workaround is to compile from source

1. install go
2. git clone https://github.com/showwin/speedtest-go.git
3. go build

**Comment by r3inbowari** [comment]
Hi, @void-fm what version of go binary are you using?

**Comment by void-fm** [comment]
> Hi, @void-fm what version of go binary are you using?

speedtest-go_1.7.9_OpenBSD_arm64.tar.gz

> 
> https://github.com/showwin/speedtest-go/blob/dd78c657d0f3a36cdf8623021fb00b0de6b3c958/speedtest/speedtest.go#L45
> 
> You can try to disable the code in this snippet. this system call interface may not be supported?

syscall(2) was removed in i think OpenBSD 7.4, might be earlier. I'm running 7.5. I didn't have to modify any code.Building from source was sufficient for it to link correctly. The sources were downloaded with git. I guess the supplied binary was built on an old openbsd instance

**Comment by r3inbowari** [comment]
> > Hi, @void-fm what version of go binary are you using?
> 
> speedtest-go_1.7.9_OpenBSD_arm64.tar.gz
> 
> > https://github.com/showwin/speedtest-go/blob/dd78c657d0f3a36cdf8623021fb00b0de6b3c958/speedtest/speedtest.go#L45
> > 
> > You can try to disable the code in this snippet. this system call interface may not be supported?
> 
> syscall(2) was removed in i think OpenBSD 7.4, might be earlier. I'm running 7.5. I didn't have to modify any code.Building from source was sufficient for it to link correctly. The sources were downloaded with git. I guess the supplied binary was built on an old openbsd instance

OK

**Comment by r3inbowari** [comment]
https://go-review.googlesource.com/c/go/+/582256 maybe we need to upgrade the go version in ci goreleaser to 1.23.2.

**Comment by void-fm** [comment]
% date && uname -mrsv && go version
Wed Oct 30 12:28:01 GMT 2024
OpenBSD 7.6 GENERIC.MP#219 arm64
go version go1.23.1 openbsd/arm64

**Comment by void-fm** [comment]
os version was updated a couple of days ago

**Comment by r3inbowari** [comment]
there is a question about whether upgrading goreleaser will cause the package size to become larger.

**Comment by r3inbowari** [comment]
we have used the latest go toolchains in goreleaser.
