### ISSUE TITLE
Live/Stream Download & Upload speeds?

### ISSUE THREAD

**Issue by freitzzz** [showwin/speedtest-go#234]
Hi

I'm figuring out how to print the current download/upload speed every 300ms, just like in the browser version. Is it possible with the library?

Thanks!

**Comment by freitzzz** [comment]
Oops, shouldn't have raised this ticket so early. Figured it out after playing around with the API.
`SetCallbackDownload`

**Comment by r3inbowari** [comment]
> `SetCallbackDownload`

This can be achieved by matching the sampling interval.
