### ISSUE TITLE
Complain about  lack of lpthread/glibc on Openwrt 19.07.5 x86_64

### ISSUE THREAD

**Issue by hathlife** [showwin/speedtest-go#30]
Openwrt uses musl as its C library.
Download from release package→ fail to run. 
Go API(openwrt golang 1.13 package along with gcc)→error due to "lack of -lpthread". 
Manually sideload sgerrand/alpine-pkg-glibc (alpine linux also use musl c, so it theoretically works ) →works normally.

**Comment by showwin** [comment]
Hi, thank you for using speedtest-go!
Oh, I feel that was a hard way. 

How can I help you?
Or could you just share this valueble information?

**Comment by hathlife** [comment]
Update: wrote a Makefile to build the speetest-go as a openwrt package, worked as expected on x86_64 platform, but on soft-float mipsle router (MT7621 on newifi d2) there'll a panic due to "invalid memory address or nil pointer dereference".
