### ISSUE TITLE
Is there a possiblity for this tool to work with https://github.com/miquels/speedtest

### ISSUE THREAD

**Issue by elico** [showwin/speedtest-go#32]
I have been using https://github.com/miquels/speedtest in production for at-least 2-3 years now and it works great in web browsers.
However for speeds above 500 Mbps some clients browsers are not able to cope with the speed.
I have tested with your tool and it seem to work better for these clients then the browser.

I want to test it against the local speedtest server only and it uses port 4000 or 40001 with tls.
The speed test server is at:
https://speed.rimon.net.il/

and is publicly available.

**Comment by showwin** [comment]
Hi, @elico :hand: 
I'm sorry, but I'm not clear what you want to do.

Do you want to use [showwin/speedtest-go](https://github.com/showwin/speedtest-go) as a backend algorithm of [miquels/speedtest](https://github.com/miquels/speedtest) ?
If so, our speed testing algorithm is written in [here](https://github.com/showwin/speedtest-go/blob/master/speedtest/request.go#L19-L137). And you could propose this algorithm to [miquels/speedtest](https://github.com/miquels/speedtest) with creating issue.

>I want to test it against the local speedtest server only and it uses port 4000 or 40001 with tls.
The speed test server is at: https://speed.rimon.net.il/

Do you want to test speed from somewhere to https://speed.rimon.net.il:4000 or https://speed.rimon.net.il:40001 ?
This tools doesn't support testing to custom host and port. Only servers which could be found by `$ speedtest --list` are supported.

**Comment by elico** [comment]
@showwin Raised an issue there https://github.com/miquels/speedtest/issues/24
The speedtest server is quite capable to GB's of traffic so it would be pretty nice to see how it works.
A combination of the server and the client side can deliver speedtest which might be better suited for desktops compared
to browsers which sometimes can reach max of 400Mbps on home desktops.
