### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by ovaldi** [showwin/speedtest-go#34]
Hi @showwin could you have a look?

After run `brew install speedtest` for a while, I got an error:

![image](https://user-images.githubusercontent.com/4537336/112990872-1d263880-9199-11eb-9639-d5c0ca438349.png)

Mac, go@1.16.2

**Comment by showwin** [comment]
HI @ovaldi, thank you for using this tool.

If you install speedtest-go from Homebrew, you don't need to build from the source.
```
$ brew tap showwin/speedtest
$ brew install speedtest
$ speedtest --help
usage: speedtest [<flags>]

Flags:
      --help               Show context-sensitive help (also try --help-long and --help-man).
  -l, --list               Show available speedtest.net servers.
  -s, --server=SERVER ...  Select server id to speedtest.
      --saving-mode        Using less memory (≒10MB), though low accuracy (especially > 30Mbps).
      --version            Show application version.
```

In case you want to build it from the source, following commands may work well:
```
$ git clone git@github.com:showwin/speedtest-go.git
$ cd speedtest-go
$ go mod init
$ go build -o speedtest-go 
```

Be careful that `$ go build -o speedtest` may not go well, because `./speedtest` directory is already exists in this project.

**Comment by ovaldi** [comment]
@showwin thanks for your response, so the `homebrew-speedtest` script should remove the line 16?

https://github.com/showwin/homebrew-speedtest/blob/master/speedtest.rb#L16
![image](https://user-images.githubusercontent.com/4537336/113082435-09b4b500-920d-11eb-9b8d-85af8618cd40.png)

**Comment by showwin** [comment]
@ovaldi 
I'm sorry. I had misunderstand that you run:
```
$ brew install speedtest
$ go get gopkg.in/alecthomas/kingpin.v2
$ go build -o speedtest
``` 

As you mentioned, this is a bug of https://github.com/showwin/homebrew-speedtest.
I've already fixed this bug. You may install correctly by executing following commands:

```
$ brew tap showwin/speedtest
$ brew install speedtest
```

If this doesn't work well, please try `$ brew uninstall speedtest` and `$ brew untap showwin/speedtest` before installation.

Finally, thank you for your reporting bug 🤩
