### ISSUE TITLE
--json flag is not working

### ISSUE THREAD

**Issue by ZivHong** [showwin/speedtest-go#49]
It went wrong when I appended the _--json_ flag either in ubuntu20.04 or win10.
My speedtest-go version is 1.1.2.

**Comment by showwin** [comment]
Thank you for using speedtest-go and reporting😄 

I'm sorry for your inconvenience. I've just released [v1.1.3](https://github.com/showwin/speedtest-go/releases/tag/v1.1.3) which includes `--json` option 👍
