### ISSUE TITLE
Negative Result in Some Network

### ISSUE THREAD

**Issue by unsetopt** [showwin/speedtest-go#57]
Used as Go package:

```
Latency: 125.154176ms
Download: -213.915 Mbps
Upload: -208.19 Mbps
```

**Comment by nullbio** [comment]
> Used as Go package:
> 
> ```
> Latency: 125.154176ms
> Download: -213.915 Mbps
> Upload: -208.19 Mbps
> ```

I'm curious, do those figures make sense for your connection if they were positive values? (i.e., are they valid figures, but for some reason have a negative sign in front?)

**Comment by showwin** [comment]
@unsetopt Thank you for reporting a issue!

I hope https://github.com/showwin/speedtest-go/pull/66 change will solve this issue.
