### ISSUE TITLE
fetching server list failed: unable to retrieve server list error when running at :00 and :30 minutes of the hour

### ISSUE THREAD

**Issue by phantomski77** [showwin/speedtest-go#61]
Hi,

I've noticed this error while running [InfluxData's Telegraf](https://github.com/influxdata/telegraf), which is using your speedtest-go as upstream library for their [internet_speed plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internet_speed). Whenever this plugin runs at exactly :00 or :30 minutes every hour, it always fails, producing this error:
```
fetching server list failed: unable to retrieve server list
```
This was also confirmed by running the binary itself using cron, so it's not just the plugin itself - see the [discussion here](https://github.com/influxdata/telegraf/issues/9852).

**Comment by showwin** [comment]
@phantomski77 Thank you for reporting!
I wish https://github.com/showwin/speedtest-go/pull/63 change will help you 🙏
