### ISSUE TITLE
Failed to fetch user info

### ISSUE THREAD

**Issue by mikaelpeltier** [showwin/speedtest-go#79]
I tried to used internet_speed plugin of telegraf and it failed with the following error:

`2022-11-09T15:03:00Z E! [inputs.internet_speed] Error in plugin: fetching user info failed: EOF`

The error comes from the [FetchUserInfoContext method](https://github.com/showwin/speedtest-go/blob/1e6885016b2f460031f570faec0025f51b26eeec/speedtest/user.go#L37) of the speedtest-go project.

I wonder if the problem is not related to the fact that the `user-agent` of the http request is not initialized.

**Comment by showwin** [comment]
Hi @mikaelpeltier ✋ 

The user info is coming from [here](https://github.com/showwin/speedtest-go/blob/66933e12625d27e16057e6201022d037a7ef5825/speedtest/user.go#L43), and it just sends a request to https://www.speedtest.net/speedtest-config.php ([ref](https://github.com/showwin/speedtest-go/blob/66933e12625d27e16057e6201022d037a7ef5825/speedtest/user.go#L13)). If you access to the page via your browser, you should get your location and other data with XML format. 
So I guess the problem is that the user info cannot be calculated correctly on the environment you executed telegraf. I took a look at [the original issue at telegraf](https://github.com/influxdata/telegraf/issues/12213), and it looks like you run it on Docker, so I recommend you execute the following command inside the container to check if you can get the response correctly.
```
$ curl https://www.speedtest.net/speedtest-config.php
```

**Comment by mikaelpeltier** [comment]
I already checked this and there is no problem, below is the result:
```
docker run -it -v $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro telegraf curl https://www.speedtest.net/speedtest-config.php
<?xml version="1.0" encoding="UTF-8"?>
<settings>
<client ip="XX.XXX.XXX.XXX" lat="XX.XXXX" lon="-X.XXXX" isp="XXX" isprating="3.7" rating="0" ispdlavg="0" ispulavg="0" loggedin="0" country="FR" />
<server-config threadcount="4" ignoreids="" notonmap="" forcepingid="" preferredserverid=""/>
<licensekey>f7a45ced624d3a70-1df5b7cd427370f7-b91ee21d6cb22d7b</licensekey>
<customer>speedtest</customer>
<odometer start="19601573884" rate="12"/>
<times dl1="5000000" dl2="35000000" dl3="800000000" ul1="1000000" ul2="8000000" ul3="35000000"/>
<download testlength="10" initialtest="250K" mintestsize="250K" threadsperurl="4"/>
<upload testlength="10" ratio="5" initialtest="0" mintestsize="32K" threads="2" maxchunksize="512K" maxchunkcount="50" threadsperurl="4"/>
<latency testlength="10" waittime="50" timeout="20"/>
<socket-download testlength="15" initialthreads="4" minthreads="4" maxthreads="32" threadratio="750K" maxsamplesize="5000000" minsamplesize="32000" startsamplesize="1000000" startbuffersize="1" bufferlength="5000" packetlength="1000" readbuffer="65536"/>
<socket-upload testlength="15" initialthreads="dyn:tcpulthreads" minthreads="dyn:tcpulthreads" maxthreads="32" threadratio="750K" maxsamplesize="1000000" minsamplesize="32000" startsamplesize="100000" startbuffersize="2" bufferlength="1000" packetlength="1000" disabled="false"/>
<socket-latency testlength="10" waittime="50" timeout="20"/>
<translation lang="xml">
</translation>
```

For information, the sample test program provided into the README file does not work on my windows, probably for the same reason.

**Comment by r3inbowari** [comment]
Hi, I think the `EOF` may come from the request with an unclosed xml attribute `<settings></settings>`

**Comment by mikaelpeltier** [comment]
I think no, because I just wrongly cut/paste the result, I forgot the last line of the curl result.
The full result is here
```
<?xml version="1.0" encoding="UTF-8"?>
<settings>
<client ip="88.167.132.144" lat="48.1137" lon="-1.5293" isp="Free SAS" isprating="3.7" rating="0" ispdlavg="0" ispulavg="0" loggedin="0" country="FR" />
<server-config threadcount="4" ignoreids="" notonmap="" forcepingid="" preferredserverid=""/>
<licensekey>f7a45ced624d3a70-1df5b7cd427370f7-b91ee21d6cb22d7b</licensekey>
<customer>speedtest</customer>
<odometer start="19601573884" rate="12"/>
<times dl1="5000000" dl2="35000000" dl3="800000000" ul1="1000000" ul2="8000000" ul3="35000000"/>
<download testlength="10" initialtest="250K" mintestsize="250K" threadsperurl="4"/>
<upload testlength="10" ratio="5" initialtest="0" mintestsize="32K" threads="2" maxchunksize="512K" maxchunkcount="50" threadsperurl="4"/>
<latency testlength="10" waittime="50" timeout="20"/>
<socket-download testlength="15" initialthreads="4" minthreads="4" maxthreads="32" threadratio="750K" maxsamplesize="5000000" minsamplesize="32000" startsamplesize="1000000" startbuffersize="1" bufferlength="5000" packetlength="1000" readbuffer="65536"/>
<socket-upload testlength="15" initialthreads="dyn:tcpulthreads" minthreads="dyn:tcpulthreads" maxthreads="32" threadratio="750K" maxsamplesize="1000000" minsamplesize="32000" startsamplesize="100000" startbuffersize="2" bufferlength="1000" packetlength="1000" disabled="false"/>
<socket-latency testlength="10" waittime="50" timeout="20"/>
<translation lang="xml">
</translation>

</settings>
```

**Comment by showwin** [comment]
@mikaelpeltier Sorry, I'm not sure of the root cause. If the problem is solved when you add `User-Agent` header to the HTTP request, could you create a Pull Request with that fix? 🙏

**Comment by mikaelpeltier** [comment]
I uploaded https://github.com/showwin/speedtest-go/pull/80.
I Let you decide if it could be merged or if the fix should be done in other way.

**Comment by showwin** [comment]
@mikaelpeltier Thank you for your PR 👍 
I release [v1.2.1](https://github.com/showwin/speedtest-go/releases/tag/v1.2.1) which includes your fix.
