### ISSUE TITLE
feature request: add option to select the interface on linux

### ISSUE THREAD

**Issue by Simperdy** [showwin/speedtest-go#95]
Is it possible that you could add an option to select the interface when using speedtest-go on linux?

I have a Linux server which has multiple internet uplinks on different interfaces.

**Comment by r3inbowari** [comment]
Hi, @Simperdy `net.Dialer` has a field LocalAddr, which specifies the local address of the connection. We can use the custom `Speedtest.Client` to specify the outbound interface.

**Comment by Simperdy** [comment]
Hi @r3inbowari, that sounds great. How can I use it? Is it already implemented in the latest speedtest-go Client and I didn't found the switch to use it?

**Comment by r3inbowari** [comment]
@Simperdy I totally agree with your idea👍. This feature is very nice, especially when testing the speed of a single network card on a host with multiple network cards. And this PR may also work with #22 at the same time. So I try to send a PR(https://github.com/showwin/speedtest-go/pull/96) to support the feature. Please check it, @showwin thank you very much!

Finally, I provide a pre-built version for linux_amd64 here:  
[speedtest-go_outbound_linux_amd64.zip](https://github.com/showwin/speedtest-go/files/10725898/speedtest-go_outbound.zip)

You can select an outbound interface (yourip) with this command:
`./speedtest --outbound=tcp://yourip`
